### ISSUE TITLE
Please provide iPython 3.0.0 Notebook Instructions

### ISSUE THREAD

**Issue by psnively** [jove-sh/jove-spark#2]
First, thanks for your hard work on this project! It's very exciting!

I would very much like to use it with the new iPython Notebook, primarily so that I can also use the [RISE](https://github.com/damianavila/RISE) slideshow extension for presentations. It would be great if you could document how to use jove-spark as a kernel with the new iPython Notebook, in addition to in the console. If I figure it out myself in the meantime, I'll send the information to you, of course :-)

Thanks again!

**Comment by alexarchambault** [comment]
Hi,

I have something that works locally, that I pushed a few minutes ago. I'm waiting for the all the Travis build to pass, and I'll add instructions to do just that in the README. Wait for them!

**Comment by alexarchambault** [comment]
I updated the README with new instructions, thanks for your comment. Tell me if anything is unclear to you, or if you run into any new issue.
